// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC21kN2VbhCtWU7U60BYEjN10eqmP5of2Y',
    appId: '1:257463681924:web:e7d44448f1b0c87336d3d1',
    messagingSenderId: '257463681924',
    projectId: 'decisionlite-bb366',
    authDomain: 'decisionlite-bb366.firebaseapp.com',
    storageBucket: 'decisionlite-bb366.firebasestorage.app',
    measurementId: 'G-5L5JE9RDCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSrU24wtErNDSmVBKgcg_5KbbWS-nKhvg',
    appId: '1:257463681924:android:d402a7fa7b8bf6a436d3d1',
    messagingSenderId: '257463681924',
    projectId: 'decisionlite-bb366',
    storageBucket: 'decisionlite-bb366.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC21kN2VbhCtWU7U60BYEjN10eqmP5of2Y',
    appId: '1:257463681924:web:973b2eda5059893336d3d1',
    messagingSenderId: '257463681924',
    projectId: 'decisionlite-bb366',
    authDomain: 'decisionlite-bb366.firebaseapp.com',
    storageBucket: 'decisionlite-bb366.firebasestorage.app',
    measurementId: 'G-5CCJ8SMQXK',
  );
}
